CREATE TABLE IF NOT EXISTS user_profile
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT  NOT NULL,
    is_new_user           BOOLEAN NOT NULL,
    is_student            BOOLEAN NOT NULL,
    is_corporate_client   BOOLEAN NOT NULL,
    is_senior             BOOLEAN NOT NULL,
    has_referral_link     BOOLEAN NOT NULL,
    stay_duration_days    INT     NOT NULL,
    is_local_resident     BOOLEAN NOT NULL,
    has_children          BOOLEAN NOT NULL,
    is_vip_client         BOOLEAN NOT NULL,
    booking_in_off_season BOOLEAN NOT NULL,
    booking_in_off_days   INT     NOT NULL,
    booking_advance_days  INT     NOT NULL,
    booking_last_minute   BOOLEAN NOT NULL,
    is_birthday           BOOLEAN NOT NULL,
    adventure_package     BOOLEAN NOT NULL,

    CONSTRAINT fk_user_profile_user_id
        FOREIGN KEY (user_id) REFERENCES user_info (id)
            ON DELETE CASCADE
);
CREATE SEQUENCE user_profile_sequence  START 1 INCREMENT 1;

